[package]
name = "latency-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.20"
tokio = { version = "1.32", features = ["full"] }
tokio-tungstenite = "0.20"
futures = "0.3"
